#!/bin/bash

##########################
# This is a script to check Node-Health.
# Author:  Prathamesh W
# DAte:    04/02/2026
# Version: v1
###########################


# set command it show output along with command OR you can use echo "" command.

set -x #debug mode
set -e #exit the script when there is an error
set -o pipefail

#echo "Disk Space"
df -Th

#echo "Memory"
free -g

#echo "CPU"
nproc
